# Generated by Django 2.1.5 on 2021-06-22 00:34

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=500)),
            ],
        ),

        migrations.AddField(
            model_name='post',
            name='queries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.queries'),
        ),
    ]
